<a href="https://colab.research.google.com/github/databyhuseyn/DeepLearning/blob/main/Diamond_Prices_Prediction_with_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!/bin/bash
!curl -L -o diamonds-price-dataset.zip https://www.kaggle.com/api/v1/datasets/download/amirhosseinmirzaie/diamonds-price-dataset

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  557k  100  557k    0     0   396k      0  0:00:01  0:00:01 --:--:-- 1233k

In [2]:
from zipfile import ZipFile

In [3]:
with ZipFile('/content/diamonds-price-dataset.zip','r') as f:
  f.extractall()

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/diamonds.csv')
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
49995   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
49996   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
49997   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
49998   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
49999   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[50000 rows x 10 columns]

In [6]:
X = df.drop(['price'], axis=1)
y = df['price'].copy()

In [7]:
X

       carat        cut color clarity  depth  table     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
49995   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50
49996   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61
49997   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56
49998   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74
49999   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64

[50000 rows x 9 columns]

In [8]:
df.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
import numpy as np

In [12]:
num_features = X_train.select_dtypes(include=[np.number]).columns
cat_features = X_train.select_dtypes(exclude=[np.number]).columns

In [13]:
cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

transformer = ColumnTransformer([
    ('cat', cat_pipeline, cat_features),
    ('num', num_pipeline, num_features)
])

In [14]:
X_train_transformed = transformer.fit_transform(X_train)
X_train_transformed

array([[ 0.        ,  0.        ,  0.        , ...,  0.83257753,
         0.84238548,  0.80071453],
       [ 0.        ,  0.        ,  1.        , ..., -1.09065123,
        -1.10013247, -1.07325525],
       [ 0.        ,  0.        ,  0.        , ...,  0.80586602,
         0.72965007,  0.73026454],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.74340159,
        -0.76192622, -0.79145529],
       [ 0.        ,  1.        ,  0.        , ...,  1.34900006,
         1.37137475,  1.29386447],
       [ 0.        ,  0.        ,  0.        , ...,  0.04903988,
         0.01854975, -0.15740536]])

In [15]:
columns = transformer.get_feature_names_out()

In [16]:
X_train_transformed_df = pd.DataFrame(X_train_transformed, columns=columns)
X_train_transformed_df

,cat__cut_Fair,cat__cut_Good,cat__cut_Ideal,cat__cut_Premium,cat__cut_Very Good,cat__color_D,cat__color_E,cat__color_F,cat__color_G,cat__color_H,...,cat__clarity_VS1,cat__clarity_VS2,cat__clarity_VVS1,cat__clarity_VVS2,num__carat,num__depth,num__table,num__x,num__y,num__z
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.694303,-0.247057,1.583210,0.832578,0.842385,0.800715
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,-0.966511,0.032562,-0.652848,-1.090651,-1.100132,-1.073255
2,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.631234,-0.177152,1.135998,0.805866,0.729650,0.730265
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,-0.167639,-4.441334,2.924844,0.289443,0.200661,-0.284215
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.421004,-1.016008,0.241575,0.672308,0.608243,0.504825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.209685,-0.456771,-0.652848,-0.004383,0.018550,-0.030595
39996,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.556244,-0.596580,0.688786,1.625019,1.492782,1.448854
39997,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-0.777305,-0.456771,0.241575,-0.743402,-0.761926,-0.791455
39998,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.472153,-0.386866,1.583210,1.349000,1.371375,1.293864
39999,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,-0.209685,-1.645149,0.688786,0.049040,0.018550,-0.157405

In [17]:
X_test_transformed = transformer.transform(X_test)
X_test_transformed

array([[ 0.        ,  0.        ,  0.        , ...,  0.6099816 ,
         0.54753901,  0.65981455],
       [ 0.        ,  0.        ,  1.        , ..., -1.04613205,
        -1.00474096, -1.03098526],
       [ 0.        ,  0.        ,  0.        , ...,  0.81476985,
         0.76433789,  0.87116452],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.07561383,
        -0.0508259 ,  0.06803461],
       [ 0.        ,  0.        ,  0.        , ...,  0.89490438,
         0.83371353,  0.78662453],
       [ 0.        ,  0.        ,  1.        , ...,  0.49423173,
         0.52152314,  0.36392458]])

In [18]:
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=columns)
X_test_transformed_df

,cat__cut_Fair,cat__cut_Good,cat__cut_Ideal,cat__cut_Premium,cat__cut_Very Good,cat__color_D,cat__color_E,cat__color_F,cat__color_G,cat__color_H,...,cat__clarity_VS1,cat__clarity_VS2,cat__clarity_VVS1,cat__clarity_VVS2,num__carat,num__depth,num__table,num__x,num__y,num__z
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.442027,0.661703,-1.547272,0.609982,0.547539,0.659815
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,-0.945488,-0.177152,-0.652848,-1.046132,-1.004741,-1.030985
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.694303,0.661703,-0.205637,0.814770,0.764338,0.871165
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.913635,1.011226,-0.205637,1.562692,1.553486,1.702474
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,2.901714,-0.526675,1.135998,2.274999,2.247242,2.153354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-0.630144,0.451989,-0.205637,-0.627652,-0.579815,-0.551925
9996,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,-0.504006,-0.456771,-1.100060,-0.360537,-0.337000,-0.396935
9997,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,-0.188662,1.151035,0.241575,-0.075614,-0.050826,0.068035
9998,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.673280,-0.526675,0.688786,0.894904,0.833714,0.786625
9999,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.231798,-1.085912,-0.205637,0.494232,0.521523,0.363925

## DL

In [19]:
import torch.nn as nn
import torch
from torch.utils.data import TensorDataset, DataLoader

In [20]:
torch_train = torch.FloatTensor(X_train_transformed)
torch_test = torch.FloatTensor(X_test_transformed)

In [21]:
y_train = torch.FloatTensor(y_train.to_numpy()).reshape(-1, 1)
y_test = torch.FloatTensor(y_test.to_numpy()).reshape(-1, 1)

In [22]:
train_data = TensorDataset(torch_train, y_train)
test_data = TensorDataset(torch_train, y_test)

In [23]:
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32)

In [24]:
n_features = X_train_transformed.shape[1]

In [25]:
model = nn.Sequential(
    nn.Linear(in_features = n_features, out_features= 64),
    nn.ReLU(),
    nn.Linear(in_features = 64, out_features= 32),
    nn.ReLU(),
    nn.Linear(in_features = 32, out_features= 16),
    nn.ReLU(),
    nn.Linear(in_features = 16, out_features= 1),
)

In [26]:
n_params = (9 + 1) * 64 + (64+ 1) * 32 + (32 + 1) * 16 + (16 + 1) * 1
n_params

3265

In [27]:
if torch.cuda.is_available():
  device = 'cuda'
else:
  device = 'cpu'

In [28]:
def train(model, train_loader, optimizer, criterion, n_epochs):
  model.train()
  for epoch in range(n_epochs):
    total_loss = 0.
    for X_batch, y_batch in train_loader:
      X_batch, y_batch = X_batch.to(device), y_batch.to(device)
      y_pred = model(X_batch)
      loss = criterion(y_pred, y_batch)
      total_loss += loss.item()
      loss.backward()
      optimizer.step()
      optimizer.zero_grad()

    print(f'Epoch: {epoch+1}/{n_epochs}, Loss: {(total_loss / len(train_loader)) ** 0.5}')

In [29]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
mse = nn.MSELoss()

In [30]:
model = model.to(device)

In [31]:
train(model, train_loader, optimizer, mse, 20)

Epoch: 1/20, Loss: 2633.295317594003
Epoch: 2/20, Loss: 1065.31804145816
Epoch: 3/20, Loss: 966.2449209439602
Epoch: 4/20, Loss: 901.5301755782359
Epoch: 5/20, Loss: 857.9408007658512
Epoch: 6/20, Loss: 829.0735230740999
Epoch: 7/20, Loss: 804.8230114635453
Epoch: 8/20, Loss: 787.9012380011533
Epoch: 9/20, Loss: 770.4234846660634
Epoch: 10/20, Loss: 753.4656016140518
Epoch: 11/20, Loss: 737.8338012988172
Epoch: 12/20, Loss: 723.810673932374
Epoch: 13/20, Loss: 712.8150900698231
Epoch: 14/20, Loss: 701.4998011426126
Epoch: 15/20, Loss: 692.83026684932
Epoch: 16/20, Loss: 684.1111356659732
Epoch: 17/20, Loss: 676.710232578585
Epoch: 18/20, Loss: 670.30626177983
Epoch: 19/20, Loss: 665.0377877233744
Epoch: 20/20, Loss: 659.3229661815028

In [36]:
y.std()

3997.9381046393905

In [32]:
first_test_batch = next(iter(test_loader))
# test_samples = first_test_batch[:3]
new_samples = first_test_batch[0][:3]
new_samples = new_samples.to(device)

In [33]:
model.eval()

Sequential(
  (0): Linear(in_features=26, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=16, bias=True)
  (5): ReLU()
  (6): Linear(in_features=16, out_features=1, bias=True)
)

In [34]:
model(new_samples)

tensor([[6167.9629],
        [ 858.9678],
        [5003.9604]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [35]:
answers = first_test_batch[1][:3]
answers

tensor([[4276.],
        [ 478.],
        [5012.]])